sudo: required
dist: trusty

language: python
python:
  - '3.5'

before_install:
  - sudo ./etc/install_dependencies.sh
  - sudo python3 canvas --init
  - sudo chmod -R 666 ./settings.json
  - sudo -u postgres python3 canvas --init-db

script:
  - coverage run canvas --test

after_success:
  - coveralls
