sudo: required
dist: trusty

language: node_js
python:
  - '3.6'

before_install:
  - sudo ./etc/scripts/ubuntu_trusty_setup.sh

script:
  - coverage-3.6 run canvas --run_tests

after_success:
  - coveralls
