sudo: required
dist: trusty

language: python
python:
  - '3.5'

before_install:
  - ./etc/install_dependencies.sh
  - python3 canvas --init
  - -u postgres python3 canvas --apply-config

script:
  - coverage run canvas --test

after_success:
  - coveralls
