#	coding utf-8
'''
Utilities simplifying working with uploaded files by automatically serializing
any files to `FileUpload`s.
'''

import base64

from ..exceptions import Unrecognized
from ..utils import register
from .json_serializers import JSONSerializer

class FileUpload:
	'''
	An object representing a file upload as generated by the canvas front-end 
	form abstraction.
	'''

	def __init__(self, filename=None, mimetype=None, content=None):
		self.filename, self.mimetype = filename, mimetype
		self.content = base64.b64decode(content)

@register.json_serializer
class FileUploadDeserializer(JSONSerializer):

	def deserialize(self, data):
		#	Assert data is an uploaded file.
		if not isinstance(data, dict) or '_is_file' not in data:
			raise Unrecognized()
		
		del data['_is_file']
		return FileUpload(**data)
