// Generated by CoffeeScript 2.2.2
(function() {
  var modal;

  modal = new cv.Modal({
    dom: <div class=".item">{{item}}</div>,
    events: {
      '.item:click': function(e) {
        return console.log(e);
      },
      '.cancel:hover': function(e) {
        return console.log(e);
      }
    },
    style: {
      '.item': {
        'text-align': 'center'
      }
    }
  });

}).call(this);
