// Generated by CoffeeScript 2.2.2
(function() {
  var babel, coffee, jsx, opts, src;

  babel = require('babel-core');

  coffee = require('coffeescript');

  opts = {
    presets: 'es2015',
    plugins: [
      [
        'transform-react-jsx',
        {
          pragma: 'cv.tag'
        }
      ]
    ]
  };

  src = 'x = <div class="asd"></div>';

  jsx = coffee.compile(babel.transform(src, opts));

  console.log(jsx.code);

}).call(this);
